version: "3.0"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
networks:
  monitor:
    driver: bridge
volumes:
  data: {}