version: "3.0"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - data:/prometheus
      - /git/docker_images/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    networks:
      - monitor

networks:
  monitor:
    driver: bridge

volumes:
  data: {}