version: "3.0"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - data:/prometheus
      - /git/docker_images/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /docker_images/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - monitor
  zabbix:
    image: zabbix:zabbix:latest
    

networks:
  monitor:
    driver: bridge

volumes:
  data: {}
  grafana_data: {}