version: "3.0"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - data:/prometheus
      - /home/gitTest/docker_images/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /home/gitTest/docker_images/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - monitor
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibanaServer
    volumes:
      - /home/gitTest/docker_images/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: mytest.kibana.org
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - monitor
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - monitor
    ports:
      - "9200:9200"
    volumes:
      - esdata:/user/share/elasticsearch/data
    

networks:
  monitor:
    driver: bridge

volumes:
  data: {}
  grafana_data: {}